/** Researched cheap-eat spots near school areas (public listings). Coords are approximate. */
export type SpotData = {
  clusterSlug: string;
  name: string;
  address: string;
  lat: number;
  lng: number;
  avgPriceVnd: bigint;
  tags: string[];
  note: string;
  order: number;
  reviews?: { rating: number; body: string; priceVnd?: bigint; author: string }[];
};

export const FOOD_SPOTS: SpotData[] = [
  // ── Sài Gòn ─────────────────────────────────────────────────────────────
  {
    clusterSlug: "saigon",
    name: "Cơm gà nướng sữa Thái Huy",
    address: "21 Huỳnh Tịnh Của, Bình Thạnh",
    lat: 10.7984,
    lng: 106.7148,
    avgPriceVnd: 35000n,
    tags: ["rice", "under-35k"],
    note: "Cơm gà nướng sữa vàng ươm, phần từ 28–40k. Đông học sinh buổi trưa.",
    order: 0,
    reviews: [
      { rating: 5, body: "Cơm gà 35k no cả buổi chiều, nước sâm 8k rẻ.", priceVnd: 35000n, author: "Minh Anh" },
      { rating: 4, body: "Hơi đông 11h30, nên đi sớm 15 phút.", priceVnd: 32000n, author: "Tuấn" },
    ],
  },
  {
    clusterSlug: "saigon",
    name: "Cơm tấm Bà Năm",
    address: "Nguyễn Xí, Bình Thạnh",
    lat: 10.8021,
    lng: 106.7089,
    avgPriceVnd: 28000n,
    tags: ["rice", "under-35k"],
    note: "Cơm sườn + trứng, đông học sinh trưa.",
    order: 1,
    reviews: [{ rating: 5, body: "Sườn bì chả 28k, ăn no.", priceVnd: 28000n, author: "Lan" }],
  },
  {
    clusterSlug: "saigon",
    name: "Bún bò Huế cô Lan",
    address: "Điện Biên Phủ, Bình Thạnh",
    lat: 10.8003,
    lng: 106.7112,
    avgPriceVnd: 25000n,
    tags: ["noodles", "under-35k"],
    note: "Tô nhỏ 25k đủ no buổi sáng.",
    order: 2,
  },
  {
    clusterSlug: "saigon",
    name: "Trà sữa 10k Anh Ba",
    address: "Xô Viết Nghệ Tĩnh, Bình Thạnh",
    lat: 10.8034,
    lng: 106.7101,
    avgPriceVnd: 15000n,
    tags: ["bubble-tea", "under-25k"],
    note: "Size M 15k, hay có combo 2 ly giảm giá.",
    order: 3,
    reviews: [{ rating: 4, body: "Trà sữa 15k vị ổn, hợp tiền tiêu vặt.", priceVnd: 15000n, author: "Vy" }],
  },
  {
    clusterSlug: "saigon",
    name: "Bánh mì thịt nướng",
    address: "Nguyễn Hữu Cảnh, Bình Thạnh",
    lat: 10.7998,
    lng: 106.7075,
    avgPriceVnd: 15000n,
    tags: ["banh-mi", "under-25k"],
    note: "Ổ đầy, ăn nhanh trước giờ học.",
    order: 4,
  },
  {
    clusterSlug: "saigon",
    name: "Căng tin trường (cơm suất)",
    address: "Khu vực trường THPT Bình Thạnh",
    lat: 10.8018,
    lng: 106.712,
    avgPriceVnd: 22000n,
    tags: ["rice", "canteen", "under-35k"],
    note: "Suất cơm trưa học sinh — rẻ nhất nếu mua được suất.",
    order: 5,
  },
  {
    clusterSlug: "saigon",
    name: "Phở bò tái",
    address: "Bạch Đằng, Bình Thạnh",
    lat: 10.8042,
    lng: 106.7092,
    avgPriceVnd: 30000n,
    tags: ["pho", "under-35k"],
    note: "Tô vừa 30k, nước dùng ngọt xương.",
    order: 6,
  },
  {
    clusterSlug: "saigon",
    name: "Ốc tô Vạn Kiếp",
    address: "Vạn Kiếp, Bình Thạnh",
    lat: 10.8075,
    lng: 106.6942,
    avgPriceVnd: 30000n,
    tags: ["snacks", "under-35k"],
    note: "Bát ốc ~30k, hay gom bạn đi chia.",
    order: 7,
    reviews: [{ rating: 4, body: "Ốc 30k to, nhưng dễ tốn thêm nước uống.", priceVnd: 30000n, author: "Huy" }],
  },
  {
    clusterSlug: "saigon",
    name: "Bánh tráng nướng Phan Rang",
    address: "Bình Thạnh",
    lat: 10.8055,
    lng: 106.7065,
    avgPriceVnd: 25000n,
    tags: ["snacks", "under-35k"],
    note: "Bánh tráng nướng 25–35k, ăn vặt sau giờ học.",
    order: 8,
  },
  {
    clusterSlug: "saigon",
    name: "Xôi gà",
    address: "Nơ Trang Long, Bình Thạnh",
    lat: 10.8009,
    lng: 106.7135,
    avgPriceVnd: 20000n,
    tags: ["sticky-rice", "under-25k"],
    note: "Một hộp no đến chiều.",
    order: 9,
  },
  {
    clusterSlug: "saigon",
    name: "Chè đậu xanh",
    address: "Đinh Bộ Lĩnh, Bình Thạnh",
    lat: 10.8028,
    lng: 106.7068,
    avgPriceVnd: 12000n,
    tags: ["dessert", "under-25k"],
    note: "Giải khát sau giờ học.",
    order: 10,
  },
  {
    clusterSlug: "saigon",
    name: "Bimbimbap Korean Food",
    address: "Bình Thạnh",
    lat: 10.801,
    lng: 106.7125,
    avgPriceVnd: 45000n,
    tags: ["rice", "under-50k"],
    note: "Cơm trộn Hàn ~40k, chia nhóm thì hợp lý.",
    order: 11,
  },
  // ── Hà Nội ──────────────────────────────────────────────────────────────
  {
    clusterSlug: "hanoi",
    name: "Cơm tấm Tường Hân",
    address: "70 Dịch Vọng Hậu, Cầu Giấy",
    lat: 21.0285,
    lng: 105.794,
    avgPriceVnd: 35000n,
    tags: ["rice", "under-35k"],
    note: "Cơm tấm sườn bì chả, 30–50k/suất. Gần khu trường Dịch Vọng.",
    order: 0,
    reviews: [
      { rating: 5, body: "Sườn nướng thơm, suất 35k no.", priceVnd: 35000n, author: "Hà My" },
      { rating: 4, body: "Trưa đông, đợi 10 phút.", priceVnd: 40000n, author: "Quân" },
    ],
  },
  {
    clusterSlug: "hanoi",
    name: "Cơm Thố Anh Nguyễn",
    address: "Dương Khuê, Mai Dịch, Cầu Giấy",
    lat: 21.0355,
    lng: 105.7768,
    avgPriceVnd: 35000n,
    tags: ["rice", "under-35k"],
    note: "Cơm niêu/thố 30–50k, sinh viên ĐHQG hay ăn.",
    order: 1,
    reviews: [{ rating: 4, body: "Cơm thố gà 35k, lớp cháy giòn.", priceVnd: 35000n, author: "Phúc" }],
  },
  {
    clusterSlug: "hanoi",
    name: "Bún đậu Ngõ 79",
    address: "Ngõ 79 Cầu Giấy",
    lat: 21.0288,
    lng: 105.8012,
    avgPriceVnd: 33000n,
    tags: ["noodles", "under-35k"],
    note: "Suất 30–38k, gần Ngoại thương & Thương mại.",
    order: 2,
    reviews: [{ rating: 5, body: "Suất 33k đầy đậu và thịt.", priceVnd: 33000n, author: "Trang" }],
  },
  {
    clusterSlug: "hanoi",
    name: "Bánh mì Cô Hai",
    address: "76 Trần Quốc Vượng, Dịch Vọng Hậu",
    lat: 21.0298,
    lng: 105.7915,
    avgPriceVnd: 35000n,
    tags: ["banh-mi", "under-35k"],
    note: "Bánh mì Sài Gòn style, <60k bữa nhanh.",
    order: 3,
  },
  {
    clusterSlug: "hanoi",
    name: "Canteen ĐH Lao động Xã hội",
    address: "43 Trần Duy Hưng, Cầu Giấy",
    lat: 21.0125,
    lng: 105.801,
    avgPriceVnd: 15000n,
    tags: ["canteen", "rice", "under-25k"],
    note: "Cơm trưa 6–20k nếu vào được — rẻ nhất khu vực.",
    order: 4,
    reviews: [{ rating: 5, body: "Cơm trưa 15k, rẻ mà ăn được.", priceVnd: 15000n, author: "Nam" }],
  },
  {
    clusterSlug: "hanoi",
    name: "Cơm rang dưa bò",
    address: "Xuân Thủy, Cầu Giấy",
    lat: 21.0375,
    lng: 105.781,
    avgPriceVnd: 35000n,
    tags: ["rice", "under-35k"],
    note: "Phần đầy, học sinh hay ăn tối.",
    order: 5,
  },
  {
    clusterSlug: "hanoi",
    name: "Bún chả",
    address: "Phạm Hồng Thái, Cầu Giấy",
    lat: 21.0359,
    lng: 105.7838,
    avgPriceVnd: 30000n,
    tags: ["noodles", "under-35k"],
    note: "Suất học sinh 30k, thịt nhiều.",
    order: 6,
  },
  {
    clusterSlug: "hanoi",
    name: "Trà chanh vỉa hè",
    address: "Trần Thái Tông, Cầu Giấy",
    lat: 21.0382,
    lng: 105.7802,
    avgPriceVnd: 10000n,
    tags: ["bubble-tea", "under-25k"],
    note: "Ngồi học nhóm rẻ — 10k/ly.",
    order: 7,
  },
  {
    clusterSlug: "hanoi",
    name: "Bánh mì chảo",
    address: "Phạm Văn Đồng, Cầu Giấy",
    lat: 21.0348,
    lng: 105.7845,
    avgPriceVnd: 25000n,
    tags: ["banh-mi", "under-35k"],
    note: "No lâu, ăn trưa nhanh.",
    order: 8,
  },
  {
    clusterSlug: "hanoi",
    name: "Căng tin THPT (cơm phần)",
    address: "Khu trường Cầu Giấy",
    lat: 21.0362,
    lng: 105.7855,
    avgPriceVnd: 20000n,
    tags: ["canteen", "rice", "under-35k"],
    note: "Giá suất học sinh, khẩu phần vừa.",
    order: 9,
  },
  {
    clusterSlug: "hanoi",
    name: "Phở gà",
    address: "Nguyễn Phong Sắc, Cầu Giấy",
    lat: 21.0391,
    lng: 105.7818,
    avgPriceVnd: 28000n,
    tags: ["pho", "under-35k"],
    note: "Phở gà ta, nước trong.",
    order: 10,
  },
  {
    clusterSlug: "hanoi",
    name: "Nem rán",
    address: "Hoàng Quốc Việt, Cầu Giấy",
    lat: 21.0352,
    lng: 105.7795,
    avgPriceVnd: 15000n,
    tags: ["snacks", "under-25k"],
    note: "5k/cái, mua 3 cái 15k ăn chiều.",
    order: 11,
  },
  {
    clusterSlug: "hanoi",
    name: "Sữa chua nếp cẩm",
    address: "Cầu Giấy",
    lat: 21.037,
    lng: 105.783,
    avgPriceVnd: 15000n,
    tags: ["dessert", "under-25k"],
    note: "Tráng miệng rẻ gần trường.",
    order: 12,
  },
  {
    clusterSlug: "hanoi",
    name: "Chợ Nhà Xanh (ăn vặt)",
    address: "Ngõ 130 Xuân Thủy, Cầu Giấy",
    lat: 21.0365,
    lng: 105.779,
    avgPriceVnd: 20000n,
    tags: ["snacks", "under-35k"],
    note: "Nhiều quán nhỏ 10–40k, đi nhóm thử nhiều món.",
    order: 13,
  },
];

export const FOOD_CLUSTERS = [
  {
    slug: "saigon",
    city: "saigon",
    order: 0,
    lat: 10.8015,
    lng: 106.7098,
    name: "Sài Gòn",
    description: "Quán ăn giá học sinh quanh trường THPT — khu Bình Thạnh, Q.1, Q.3.",
  },
  {
    slug: "hanoi",
    city: "hanoi",
    order: 1,
    lat: 21.0368,
    lng: 105.7821,
    name: "Hà Nội",
    description: "Căng tin, cơm bình dân quanh trường THPT và khu Cầu Giấy.",
  },
] as const;
